# -*- coding: utf-8 -*-
"""Database_Exploration_Cleaning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1krecNmlJJbqhIXoZ2_cjd7EmDZoGt8eC
"""

# ============================================================
# TCGA LUAD cBioPortal Dataset Exploration Script
# Google Colab Single-Cell Version
# Purpose:
#   Explore six selected cBioPortal files before building SQL/database.
#   This script DOES NOT create a database.
#   It creates decision-support reports for database design.
# ============================================================

import os
import re
import zipfile
from pathlib import Path

import pandas as pd
import numpy as np

from google.colab import drive
from google.colab import files


# ============================================================
# 1. MOUNT GOOGLE DRIVE
# ============================================================

drive.mount("/content/drive")


# ============================================================
# 2. CONFIGURATION
# ============================================================

# Folder name in Google Drive that contains your six cBioPortal files.
PROJECT_FOLDER_NAME = "luad_tcga_pub"

OUTPUT_DIR = Path("/content/luad_decision_outputs")
ZIP_PATH = Path("/content/luad_dataset_decision_report.zip")

OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

FILES_REQUIRED = {
    "clinical_patient": "data_clinical_patient.txt",
    "clinical_sample": "data_clinical_sample.txt",
    "mutations": "data_mutations.txt",
    "cna": "data_cna.txt",
    "mrna": "data_mrna_seq_v2_rsem.txt",
    "rppa": "data_rppa.txt"
}

MISSING_VALUES = [
    "NA", "N/A", "NaN", "nan", "NULL", "null",
    "[Not Available]", "Not Available", "Unknown",
    "", " "
]

DRIVER_GENES = [
    "EGFR", "KRAS", "TP53", "STK11", "KEAP1",
    "ALK", "BRAF", "MET", "ERBB2", "ROS1",
    "RET", "PIK3CA", "NF1", "RB1", "PTEN",
    "CDKN2A", "SMARCA4", "ATM"
]


# ============================================================
# 3. DRIVE PATH RESOLUTION
# ============================================================

def resolve_data_dir(folder_name):
    """
    Finds the folder containing the cBioPortal files.
    Checks common Colab Drive paths first.
    If not found, searches Google Drive.
    """

    possible_paths = [
        Path(f"/content/drive/MyDrive/{folder_name}"),
        Path(f"/content/drive/My Drive/{folder_name}")
    ]

    for path in possible_paths:
        if path.exists():
            return path

    print(f"Folder not found in standard locations. Searching Drive for: {folder_name}")
    drive_root = Path("/content/drive")

    matches = []
    for root, dirs, file_names in os.walk(drive_root):
        if Path(root).name == folder_name:
            matches.append(Path(root))

    if len(matches) == 1:
        return matches[0]

    if len(matches) > 1:
        print("Multiple matching folders found:")
        for i, match in enumerate(matches, start=1):
            print(f"{i}. {match}")
        print("Using the first match.")
        return matches[0]

    raise FileNotFoundError(
        f"Could not find folder named '{folder_name}' in Google Drive.\n"
        f"Please confirm your folder exists and is named exactly: {folder_name}\n"
        f"Expected example path: /content/drive/MyDrive/{folder_name}"
    )


DATA_DIR = resolve_data_dir(PROJECT_FOLDER_NAME)

print("\nUsing input folder:")
print(DATA_DIR)

print("\nFiles currently found in this folder:")
for p in sorted(DATA_DIR.iterdir()):
    print("-", p.name)


# ============================================================
# 4. HELPER FUNCTIONS
# ============================================================

def clean_column_name(col):
    """
    Standardizes column names.
    Example:
    Tumor Sample Barcode -> TUMOR_SAMPLE_BARCODE
    """
    col = str(col).strip()
    col = col.replace(" ", "_")
    col = col.replace("-", "_")
    col = col.replace("/", "_")
    col = re.sub(r"[^A-Za-z0-9_]", "", col)
    col = col.upper()

    if col == "":
        col = "UNNAMED_COLUMN"

    return col


def make_unique_columns(columns):
    """
    Ensures duplicate column names are made unique.
    This prevents pandas from returning a DataFrame instead of a Series
    when selecting df[col].
    """
    seen = {}
    unique_cols = []

    for col in columns:
        base = clean_column_name(col)

        if base not in seen:
            seen[base] = 0
            unique_cols.append(base)
        else:
            seen[base] += 1
            unique_cols.append(f"{base}_{seen[base]}")

    return unique_cols


def read_cbioportal_file(filepath):
    """
    Reads a cBioPortal tab-separated file.
    Skips metadata/comment rows beginning with '#'.
    Cleans column names.
    Makes duplicate column names unique.
    Converts missing labels to NaN.
    """

    if not filepath.exists():
        raise FileNotFoundError(f"Missing file: {filepath}")

    df = pd.read_csv(
        filepath,
        sep="\t",
        comment="#",
        dtype=str,
        low_memory=False
    )

    df.columns = make_unique_columns(df.columns)
    df = df.replace(MISSING_VALUES, np.nan)

    return df


def find_column(df, candidates):
    """
    Finds the first matching column from candidate column names.
    """
    cols = list(df.columns)

    for c in candidates:
        cc = clean_column_name(c)
        if cc in cols:
            return cc

    return None


def get_column_as_series(df, col):
    """
    Safely returns a column as a Series.
    If duplicate columns somehow still exist, takes the first one.
    """
    obj = df[col]

    if isinstance(obj, pd.DataFrame):
        return obj.iloc[:, 0]

    return obj


def derive_patient_barcode_from_sample(sample_barcode):
    """
    TCGA patient barcode is usually first 12 characters.
    Example:
    TCGA-05-4244-01 -> TCGA-05-4244
    """
    if pd.isna(sample_barcode):
        return np.nan

    sample_barcode = str(sample_barcode).strip()

    if sample_barcode.startswith("TCGA") and len(sample_barcode) >= 12:
        return sample_barcode[:12]

    return sample_barcode


def summarize_missingness(df, dataset_name):
    """
    Summarizes missingness, unique values, and example values for each column.
    Fixed to safely handle duplicate column names.
    """

    rows = []

    for col in df.columns:
        series = get_column_as_series(df, col)

        non_null_count = int(series.notna().sum())
        null_count = int(series.isna().sum())
        missing_percent = round(float(series.isna().mean() * 100), 2)
        unique_values = int(series.nunique(dropna=True))

        example_values = ", ".join(
            series.dropna().astype(str).unique()[:5]
        )

        rows.append({
            "DATASET": dataset_name,
            "COLUMN": col,
            "NON_NULL_COUNT": non_null_count,
            "NULL_COUNT": null_count,
            "MISSING_PERCENT": missing_percent,
            "UNIQUE_VALUES": unique_values,
            "EXAMPLE_VALUES": example_values
        })

    return pd.DataFrame(rows).sort_values(["MISSING_PERCENT", "COLUMN"])


def get_sample_ids_from_clinical_sample(df):
    sample_col = find_column(df, ["SAMPLE_ID", "SAMPLE_BARCODE", "TUMOR_SAMPLE_BARCODE"])

    if sample_col is None:
        return set()

    s = get_column_as_series(df, sample_col)

    return set(s.dropna().astype(str).str.strip())


def get_patient_ids_from_clinical_patient(df):
    patient_col = find_column(df, ["PATIENT_ID", "PATIENT_BARCODE", "CASE_ID"])

    if patient_col is None:
        return set()

    s = get_column_as_series(df, patient_col)

    return set(s.dropna().astype(str).str.strip())


def get_sample_ids_from_mutation(df):
    sample_col = find_column(df, ["TUMOR_SAMPLE_BARCODE", "SAMPLE_ID", "SAMPLE_BARCODE"])

    if sample_col is None:
        return set()

    s = get_column_as_series(df, sample_col)

    return set(s.dropna().astype(str).str.strip())


def get_gene_symbols_from_mutation(df):
    gene_col = find_column(df, ["HUGO_SYMBOL", "GENE", "GENE_SYMBOL"])

    if gene_col is None:
        return set()

    s = get_column_as_series(df, gene_col)

    return set(s.dropna().astype(str).str.upper().str.strip())


def identify_matrix_gene_column(df):
    """
    Finds the gene or feature column in matrix-style files.
    If no recognized gene column exists, uses the first column.
    """
    gene_col = find_column(df, ["HUGO_SYMBOL", "GENE", "GENE_SYMBOL", "COMPOSITE_ELEMENT_REF"])

    if gene_col is not None:
        return gene_col

    return df.columns[0]


def get_gene_symbols_from_matrix(df):
    gene_col = identify_matrix_gene_column(df)
    s = get_column_as_series(df, gene_col)

    return set(s.dropna().astype(str).str.upper().str.strip())


def get_sample_ids_from_matrix(df):
    """
    Gets sample IDs from matrix-style files.
    Excludes likely annotation columns.
    """

    gene_col = identify_matrix_gene_column(df)

    id_cols = [gene_col]

    possible_annotation_cols = [
        "ENTREZ_GENE_ID",
        "GENE_ID",
        "CYTOBAND",
        "DESCRIPTION",
        "ANTIBODY_REF",
        "PROTEIN_NAME",
        "RPPA_ID",
        "COMPOSITE_ELEMENT_REF",
        "ENTITY_STABLE_ID",
        "REFSEQ_PROTEIN_ID"
    ]

    for col in possible_annotation_cols:
        c = clean_column_name(col)
        if c in df.columns and c not in id_cols:
            id_cols.append(c)

    sample_cols = [c for c in df.columns if c not in id_cols]

    return set(sample_cols)


def get_driver_gene_presence(gene_sets):
    rows = []

    for gene in DRIVER_GENES:
        row = {"GENE": gene}

        for dataset_name, genes in gene_sets.items():
            row[dataset_name] = "YES" if gene in genes else "NO"

        rows.append(row)

    return pd.DataFrame(rows)


def recommend_column_status(column_name):
    """
    Gives a rough recommendation for whether a column may be useful.
    """

    col = column_name.upper()

    high_value_keywords = [
        "PATIENT", "SAMPLE", "BARCODE", "SEX", "GENDER", "AGE",
        "OS", "SURVIVAL", "STATUS", "MONTHS",
        "STAGE", "TUMOR", "METASTASIS", "SMOKING",
        "HISTOLOGICAL", "CANCER_TYPE", "SUBTYPE",
        "TMB", "MUTATION_COUNT", "FRACTION_GENOME_ALTERED",
        "HUGO", "ENTREZ", "CHROMOSOME", "START", "END",
        "VARIANT", "ALLELE", "CONSEQUENCE", "IMPACT",
        "PROTEIN", "CODON", "T_ALT", "T_REF"
    ]

    derived_or_complex_keywords = [
        "Z_SCORE", "ZSCORE", "P_VALUE", "Q_VALUE",
        "URL", "LINK", "COMMENT", "NOTES"
    ]

    if any(k in col for k in derived_or_complex_keywords):
        return "LOW PRIORITY / POSSIBLY EXCLUDE"

    if any(k in col for k in high_value_keywords):
        return "KEEP / REVIEW FOR DATABASE"

    return "REVIEW"


def make_column_decision_summary(df, dataset_name):
    missing = summarize_missingness(df, dataset_name)
    missing["RECOMMENDATION"] = missing["COLUMN"].apply(recommend_column_status)
    return missing


def save_df(df, filename):
    path = OUTPUT_DIR / filename
    df.to_csv(path, index=False)
    return path


# ============================================================
# 5. CHECK AND LOAD FILES
# ============================================================

print("\nChecking required files...")

missing_files = []

for label, filename in FILES_REQUIRED.items():
    path = DATA_DIR / filename
    if not path.exists():
        missing_files.append(filename)

if missing_files:
    print("\nERROR: Missing required files:")
    for f in missing_files:
        print("-", f)

    print("\nFiles available in your folder:")
    for p in sorted(DATA_DIR.iterdir()):
        print("-", p.name)

    raise FileNotFoundError(
        "One or more required files are missing. "
        "Check file names exactly, including capitalization."
    )

print("All six required files found.")

print("\nLoading files...")

clinical_patient = read_cbioportal_file(DATA_DIR / FILES_REQUIRED["clinical_patient"])
clinical_sample = read_cbioportal_file(DATA_DIR / FILES_REQUIRED["clinical_sample"])
mutations = read_cbioportal_file(DATA_DIR / FILES_REQUIRED["mutations"])
cna = read_cbioportal_file(DATA_DIR / FILES_REQUIRED["cna"])
mrna = read_cbioportal_file(DATA_DIR / FILES_REQUIRED["mrna"])
rppa = read_cbioportal_file(DATA_DIR / FILES_REQUIRED["rppa"])

datasets = {
    "clinical_patient": clinical_patient,
    "clinical_sample": clinical_sample,
    "mutations": mutations,
    "cna": cna,
    "mrna": mrna,
    "rppa": rppa
}

print("Files loaded successfully.")

print("\nLoaded dataset shapes:")
for name, df in datasets.items():
    print(f"{name}: {df.shape[0]:,} rows x {df.shape[1]:,} columns")


# ============================================================
# 6. FILE SUMMARY
# ============================================================

file_summary_rows = []

for name, df in datasets.items():
    file_summary_rows.append({
        "DATASET": name,
        "ROWS": df.shape[0],
        "COLUMNS": df.shape[1],
        "COLUMN_NAMES": ", ".join(df.columns)
    })

file_summary = pd.DataFrame(file_summary_rows)
save_df(file_summary, "01_file_summary.csv")

print("\nFile Summary:")
display(file_summary[["DATASET", "ROWS", "COLUMNS"]])


# ============================================================
# 7. COLUMN MISSINGNESS AND COLUMN RECOMMENDATIONS
# ============================================================

all_column_summaries = []

for name, df in datasets.items():
    summary = make_column_decision_summary(df, name)
    save_df(summary, f"02_column_summary_{name}.csv")
    all_column_summaries.append(summary)

all_column_summary = pd.concat(all_column_summaries, ignore_index=True)
save_df(all_column_summary, "02_all_column_summaries.csv")

print("\nColumn Summary Preview:")
display(all_column_summary.head(20))


# ============================================================
# 8. PATIENT AND SAMPLE IDENTIFIER SUMMARY
# ============================================================

clinical_patient_ids = get_patient_ids_from_clinical_patient(clinical_patient)
clinical_sample_ids = get_sample_ids_from_clinical_sample(clinical_sample)
mutation_sample_ids = get_sample_ids_from_mutation(mutations)
cna_sample_ids = get_sample_ids_from_matrix(cna)
mrna_sample_ids = get_sample_ids_from_matrix(mrna)
rppa_sample_ids = get_sample_ids_from_matrix(rppa)

sample_sets = {
    "clinical_sample": clinical_sample_ids,
    "mutations": mutation_sample_ids,
    "cna": cna_sample_ids,
    "mrna": mrna_sample_ids,
    "rppa": rppa_sample_ids
}

all_sample_ids = set()

for s in sample_sets.values():
    all_sample_ids = all_sample_ids.union(s)

common_all_molecular_samples = mutation_sample_ids & cna_sample_ids & mrna_sample_ids & rppa_sample_ids
common_all_samples_plus_clinical = clinical_sample_ids & mutation_sample_ids & cna_sample_ids & mrna_sample_ids & rppa_sample_ids

sample_overlap_rows = []

for name, sample_set in sample_sets.items():
    sample_count = len(sample_set)
    in_clinical = len(sample_set & clinical_sample_ids)
    not_in_clinical = len(sample_set - clinical_sample_ids)

    sample_overlap_rows.append({
        "DATASET": name,
        "SAMPLE_COUNT": sample_count,
        "IN_CLINICAL_SAMPLE_COUNT": in_clinical,
        "NOT_IN_CLINICAL_SAMPLE_COUNT": not_in_clinical,
        "PERCENT_IN_CLINICAL_SAMPLE": round((in_clinical / sample_count * 100), 2) if sample_count > 0 else 0
    })

sample_overlap = pd.DataFrame(sample_overlap_rows)
save_df(sample_overlap, "03_sample_overlap_summary.csv")

print("\nSample Overlap Summary:")
display(sample_overlap)

sample_presence_rows = []

for sample_id in sorted(all_sample_ids):
    sample_presence_rows.append({
        "SAMPLE_BARCODE": sample_id,
        "IN_CLINICAL_SAMPLE": sample_id in clinical_sample_ids,
        "IN_MUTATIONS": sample_id in mutation_sample_ids,
        "IN_CNA": sample_id in cna_sample_ids,
        "IN_MRNA": sample_id in mrna_sample_ids,
        "IN_RPPA": sample_id in rppa_sample_ids
    })

sample_presence = pd.DataFrame(sample_presence_rows)
save_df(sample_presence, "04_sample_presence_matrix.csv")


# ============================================================
# 9. GENE OVERLAP SUMMARY
# ============================================================

mutation_genes = get_gene_symbols_from_mutation(mutations)
cna_genes = get_gene_symbols_from_matrix(cna)
mrna_genes = get_gene_symbols_from_matrix(mrna)
rppa_genes = get_gene_symbols_from_matrix(rppa)

gene_sets = {
    "mutations": mutation_genes,
    "cna": cna_genes,
    "mrna": mrna_genes,
    "rppa": rppa_genes
}

all_genes = set()

for g in gene_sets.values():
    all_genes = all_genes.union(g)

common_all_molecular_genes = mutation_genes & cna_genes & mrna_genes & rppa_genes

gene_overlap_rows = []

for name, gene_set in gene_sets.items():
    gene_count = len(gene_set)
    common_count = len(gene_set & common_all_molecular_genes)

    gene_overlap_rows.append({
        "DATASET": name,
        "GENE_COUNT": gene_count,
        "COMMON_WITH_ALL_4_DATASETS": common_count,
        "PERCENT_COMMON_WITH_ALL_4": round((common_count / gene_count * 100), 2) if gene_count > 0 else 0
    })

gene_overlap = pd.DataFrame(gene_overlap_rows)
save_df(gene_overlap, "05_gene_overlap_summary.csv")

print("\nGene Overlap Summary:")
display(gene_overlap)

gene_presence_rows = []

for gene in sorted(all_genes):
    gene_presence_rows.append({
        "GENE": gene,
        "IN_MUTATIONS": gene in mutation_genes,
        "IN_CNA": gene in cna_genes,
        "IN_MRNA": gene in mrna_genes,
        "IN_RPPA": gene in rppa_genes
    })

gene_presence = pd.DataFrame(gene_presence_rows)
save_df(gene_presence, "06_gene_presence_matrix.csv")

driver_gene_presence = get_driver_gene_presence(gene_sets)
save_df(driver_gene_presence, "07_driver_gene_presence.csv")

print("\nDriver Gene Presence:")
display(driver_gene_presence)


# ============================================================
# 10. MUTATION-SPECIFIC SUMMARY
# ============================================================

mutation_gene_col = find_column(mutations, ["HUGO_SYMBOL", "GENE", "GENE_SYMBOL"])
variant_class_col = find_column(mutations, ["VARIANT_CLASSIFICATION"])
variant_type_col = find_column(mutations, ["VARIANT_TYPE"])
impact_col = find_column(mutations, ["IMPACT"])
sample_mut_col = find_column(mutations, ["TUMOR_SAMPLE_BARCODE", "SAMPLE_ID", "SAMPLE_BARCODE"])

if mutation_gene_col:
    mutation_gene_series = get_column_as_series(mutations, mutation_gene_col)

    top_mutated_genes = (
        mutation_gene_series
        .dropna()
        .astype(str)
        .str.upper()
        .value_counts()
        .reset_index()
    )

    top_mutated_genes.columns = ["GENE", "MUTATION_RECORD_COUNT"]
    save_df(top_mutated_genes, "08_top_mutated_genes.csv")

    print("\nTop 20 Mutated Genes:")
    display(top_mutated_genes.head(20))

if variant_class_col:
    variant_class_series = get_column_as_series(mutations, variant_class_col)

    variant_class_summary = (
        variant_class_series
        .dropna()
        .value_counts()
        .reset_index()
    )

    variant_class_summary.columns = ["VARIANT_CLASSIFICATION", "COUNT"]
    save_df(variant_class_summary, "09_variant_classification_summary.csv")

    print("\nVariant Classification Summary:")
    display(variant_class_summary.head(20))

if variant_type_col:
    variant_type_series = get_column_as_series(mutations, variant_type_col)

    variant_type_summary = (
        variant_type_series
        .dropna()
        .value_counts()
        .reset_index()
    )

    variant_type_summary.columns = ["VARIANT_TYPE", "COUNT"]
    save_df(variant_type_summary, "10_variant_type_summary.csv")

if impact_col:
    impact_series = get_column_as_series(mutations, impact_col)

    impact_summary = (
        impact_series
        .dropna()
        .value_counts()
        .reset_index()
    )

    impact_summary.columns = ["IMPACT", "COUNT"]
    save_df(impact_summary, "11_mutation_impact_summary.csv")


# ============================================================
# 11. CLINICAL FIELD AVAILABILITY
# ============================================================

clinical_interest_fields = [
    "PATIENT_ID",
    "SAMPLE_ID",
    "SEX",
    "GENDER",
    "RACE",
    "ETHNICITY",
    "AGE",
    "AGE_AT_DIAGNOSIS",
    "OS_STATUS",
    "OS_MONTHS",
    "DFS_STATUS",
    "DFS_MONTHS",
    "PFS_STATUS",
    "PFS_MONTHS",
    "CANCER_TYPE",
    "CANCER_TYPE_DETAILED",
    "HISTOLOGICAL_SUBTYPE",
    "TUMOR_STAGE_2009",
    "AJCC_PATHOLOGIC_TUMOR_STAGE",
    "PATHOLOGIC_STAGE",
    "AJCC_TUMOR_PATHOLOGIC_PT",
    "AJCC_NODES_PATHOLOGIC_PN",
    "AJCC_METASTASIS_PATHOLOGIC_PM",
    "PRIMARY_TUMOR_SPREAD",
    "DISTANT_METASTASIS_SPREAD",
    "TOBACCO_SMOKING_HISTORY",
    "SMOKING_HISTORY",
    "CIGARETTE_SMOKING_HISTORY",
    "TMB_NONSYNONYMOUS",
    "TMB",
    "MUTATION_COUNT",
    "FRACTION_GENOME_ALTERED"
]

clinical_field_rows = []

for field in clinical_interest_fields:
    field_clean = clean_column_name(field)

    row = {
        "FIELD": field_clean,
        "IN_CLINICAL_PATIENT": field_clean in clinical_patient.columns,
        "IN_CLINICAL_SAMPLE": field_clean in clinical_sample.columns
    }

    if field_clean in clinical_patient.columns:
        s = get_column_as_series(clinical_patient, field_clean)

        row["PATIENT_NON_NULL_COUNT"] = int(s.notna().sum())
        row["PATIENT_MISSING_PERCENT"] = round(float(s.isna().mean() * 100), 2)
        row["PATIENT_EXAMPLES"] = ", ".join(s.dropna().astype(str).unique()[:5])
    else:
        row["PATIENT_NON_NULL_COUNT"] = np.nan
        row["PATIENT_MISSING_PERCENT"] = np.nan
        row["PATIENT_EXAMPLES"] = ""

    if field_clean in clinical_sample.columns:
        s = get_column_as_series(clinical_sample, field_clean)

        row["SAMPLE_NON_NULL_COUNT"] = int(s.notna().sum())
        row["SAMPLE_MISSING_PERCENT"] = round(float(s.isna().mean() * 100), 2)
        row["SAMPLE_EXAMPLES"] = ", ".join(s.dropna().astype(str).unique()[:5])
    else:
        row["SAMPLE_NON_NULL_COUNT"] = np.nan
        row["SAMPLE_MISSING_PERCENT"] = np.nan
        row["SAMPLE_EXAMPLES"] = ""

    clinical_field_rows.append(row)

clinical_field_availability = pd.DataFrame(clinical_field_rows)
save_df(clinical_field_availability, "12_clinical_field_availability.csv")

print("\nClinical Field Availability:")
display(clinical_field_availability)


# ============================================================
# 12. MATRIX FILE SHAPE SUMMARY
# ============================================================

matrix_summary_rows = []

for name, df in {
    "cna": cna,
    "mrna": mrna,
    "rppa": rppa
}.items():
    gene_col = identify_matrix_gene_column(df)
    sample_ids = get_sample_ids_from_matrix(df)
    gene_ids = get_gene_symbols_from_matrix(df)

    matrix_summary_rows.append({
        "DATASET": name,
        "GENE_OR_FEATURE_COLUMN": gene_col,
        "FEATURE_ROW_COUNT": df.shape[0],
        "SAMPLE_COLUMN_COUNT": len(sample_ids),
        "TOTAL_POTENTIAL_LONG_RECORDS": df.shape[0] * len(sample_ids)
    })

matrix_summary = pd.DataFrame(matrix_summary_rows)
save_df(matrix_summary, "13_matrix_file_summary.csv")

print("\nMatrix File Summary:")
display(matrix_summary)


# ============================================================
# 13. RECOMMENDED FUTURE DATABASE TABLE PLAN
# ============================================================

recommended_tables = pd.DataFrame([
    {
        "FUTURE_TABLE": "PATIENT",
        "SOURCE_FILE": "data_clinical_patient.txt",
        "KEY_INFORMATION": "Unique patient barcode",
        "WHY_NEEDED": "Links clinical outcomes to tumor samples"
    },
    {
        "FUTURE_TABLE": "PATIENT_DEMOGRAPHIC",
        "SOURCE_FILE": "data_clinical_patient.txt",
        "KEY_INFORMATION": "Sex, race, ethnicity if available",
        "WHY_NEEDED": "Basic patient-level descriptors"
    },
    {
        "FUTURE_TABLE": "PATIENT_CLINICAL",
        "SOURCE_FILE": "data_clinical_patient.txt",
        "KEY_INFORMATION": "Cancer type, histological subtype, diagnosis/treatment fields",
        "WHY_NEEDED": "Supports clinical interpretation"
    },
    {
        "FUTURE_TABLE": "PATIENT_SURVIVAL",
        "SOURCE_FILE": "data_clinical_patient.txt",
        "KEY_INFORMATION": "OS status and OS months",
        "WHY_NEEDED": "Needed for survival/outcome questions"
    },
    {
        "FUTURE_TABLE": "PATIENT_SMOKING_HISTORY",
        "SOURCE_FILE": "data_clinical_patient.txt",
        "KEY_INFORMATION": "Smoking history field if available",
        "WHY_NEEDED": "Important lung cancer risk factor"
    },
    {
        "FUTURE_TABLE": "SAMPLE",
        "SOURCE_FILE": "data_clinical_sample.txt",
        "KEY_INFORMATION": "Sample barcode, patient barcode, sample type",
        "WHY_NEEDED": "Links each tumor sample to molecular data"
    },
    {
        "FUTURE_TABLE": "SAMPLE_STAGE",
        "SOURCE_FILE": "data_clinical_sample.txt",
        "KEY_INFORMATION": "Tumor stage, TNM fields, metastasis fields",
        "WHY_NEEDED": "Connects molecular features to tumor severity"
    },
    {
        "FUTURE_TABLE": "SAMPLE_METRIC",
        "SOURCE_FILE": "data_clinical_sample.txt",
        "KEY_INFORMATION": "TMB, mutation count, fraction genome altered",
        "WHY_NEEDED": "Useful molecular burden metrics"
    },
    {
        "FUTURE_TABLE": "GENE",
        "SOURCE_FILE": "mutation, CNA, mRNA, RPPA files",
        "KEY_INFORMATION": "HUGO gene symbol and Entrez ID if available",
        "WHY_NEEDED": "Central gene dimension table"
    },
    {
        "FUTURE_TABLE": "MUTATION",
        "SOURCE_FILE": "data_mutations.txt",
        "KEY_INFORMATION": "Chromosome, position, allele, variant classification, impact, protein change",
        "WHY_NEEDED": "Stores DNA-level alteration details"
    },
    {
        "FUTURE_TABLE": "SAMPLE_MUTATION",
        "SOURCE_FILE": "data_mutations.txt",
        "KEY_INFORMATION": "Tumor sample barcode to mutation relationship",
        "WHY_NEEDED": "Shows which samples contain which mutations"
    },
    {
        "FUTURE_TABLE": "MUTATION_GENE",
        "SOURCE_FILE": "data_mutations.txt",
        "KEY_INFORMATION": "Mutation to gene relationship",
        "WHY_NEEDED": "Supports gene-level mutation analysis"
    },
    {
        "FUTURE_TABLE": "COPY_NUMBER_ALTERATION",
        "SOURCE_FILE": "data_cna.txt",
        "KEY_INFORMATION": "Gene x sample CNA values",
        "WHY_NEEDED": "Amplification/deletion analysis"
    },
    {
        "FUTURE_TABLE": "MRNA_EXPRESSION",
        "SOURCE_FILE": "data_mrna_seq_v2_rsem.txt",
        "KEY_INFORMATION": "Gene x sample RSEM values",
        "WHY_NEEDED": "Transcript expression analysis"
    },
    {
        "FUTURE_TABLE": "PROTEIN_EXPRESSION",
        "SOURCE_FILE": "data_rppa.txt",
        "KEY_INFORMATION": "Protein/antibody x sample expression values",
        "WHY_NEEDED": "Protein-level interpretation"
    }
])

save_df(recommended_tables, "14_recommended_future_tables.csv")

print("\nRecommended Future Tables:")
display(recommended_tables)


# ============================================================
# 14. WRITTEN DECISION REPORT
# ============================================================

report = f"""
LUAD cBioPortal Dataset Decision Report
======================================

Purpose:
This report summarizes the six selected cBioPortal datasets before database construction.
The goal is to decide which information should be included in a normalized lung cancer database.

Input folder:
{DATA_DIR}

Files analyzed:
1. data_clinical_patient.txt
2. data_clinical_sample.txt
3. data_mutations.txt
4. data_cna.txt
5. data_mrna_seq_v2_rsem.txt
6. data_rppa.txt


Basic File Summary:
-------------------
{file_summary[['DATASET', 'ROWS', 'COLUMNS']].to_string(index=False)}


Sample Overlap Summary:
-----------------------
{sample_overlap.to_string(index=False)}

Samples common to mutation, CNA, mRNA, and RPPA:
{len(common_all_molecular_samples)}

Samples common to clinical sample, mutation, CNA, mRNA, and RPPA:
{len(common_all_samples_plus_clinical)}


Gene Overlap Summary:
---------------------
{gene_overlap.to_string(index=False)}

Genes common to mutation, CNA, mRNA, and RPPA:
{len(common_all_molecular_genes)}


Driver Gene Presence:
---------------------
{driver_gene_presence.to_string(index=False)}


Recommended Decision:
---------------------
The six selected files are sufficient to support a meaningful lung cancer database.

Recommended future database scope:
1. Patient clinical outcome
2. Tumor sample information
3. Somatic mutation data
4. Copy-number alteration data
5. mRNA expression data
6. Protein expression data

Recommended biological story:
Patient -> Sample -> Mutation / CNA / mRNA / Protein -> Biological conclusion

Strong biological questions supported:
1. Which genes are most frequently mutated in lung adenocarcinoma?
2. Are TP53-mutated samples associated with higher TMB?
3. Do EGFR-amplified tumors show higher EGFR mRNA expression?
4. Do EGFR-amplified tumors show higher EGFR protein expression?
5. Are EGFR, KRAS, TP53, or STK11 mutations associated with survival?
6. Do copy-number gains/losses correspond to expression changes?
7. Do RNA and protein expression agree for selected driver genes?


Generated Output Files:
-----------------------
00_LUAD_dataset_decision_report.txt
01_file_summary.csv
02_all_column_summaries.csv
03_sample_overlap_summary.csv
04_sample_presence_matrix.csv
05_gene_overlap_summary.csv
06_gene_presence_matrix.csv
07_driver_gene_presence.csv
08_top_mutated_genes.csv
09_variant_classification_summary.csv
10_variant_type_summary.csv
11_mutation_impact_summary.csv
12_clinical_field_availability.csv
13_matrix_file_summary.csv
14_recommended_future_tables.csv

Use these files to finalize the database design before writing SQL or building normalized tables.
"""

report_path = OUTPUT_DIR / "00_LUAD_dataset_decision_report.txt"

with open(report_path, "w") as f:
    f.write(report)

print("\nWritten decision report created:")
print(report_path)

# ============================================================
# FORCE DOWNLOAD OUTPUT FILES DIRECTLY TO YOUR LAPTOP
# ============================================================

from google.colab import files
from pathlib import Path
import zipfile

OUTPUT_DIR = Path("/content/luad_decision_outputs")
ZIP_PATH = Path("/content/luad_dataset_decision_report.zip")

# Recreate ZIP file from all outputs
if ZIP_PATH.exists():
    ZIP_PATH.unlink()

with zipfile.ZipFile(ZIP_PATH, "w", zipfile.ZIP_DEFLATED) as zipf:
    for file_path in OUTPUT_DIR.glob("*"):
        zipf.write(file_path, arcname=file_path.name)

print(f"ZIP file ready: {ZIP_PATH}")
print("Starting download...")

files.download(str(ZIP_PATH))

# ============================================================
# 15. ZIP OUTPUT FILES
# ============================================================

if ZIP_PATH.exists():
    ZIP_PATH.unlink()

with zipfile.ZipFile(ZIP_PATH, "w", zipfile.ZIP_DEFLATED) as zipf:
    for file_path in OUTPUT_DIR.glob("*"):
        zipf.write(file_path, arcname=file_path.name)

print("\n============================================================")
print("DONE")
print("============================================================")
print(f"Decision files saved to: {OUTPUT_DIR}")
print(f"ZIP file created at: {ZIP_PATH}")
print("============================================================")

files.download(str(ZIP_PATH))

# ============================================================
# TCGA LUAD cBioPortal Data Cleaning Pipeline - Google Colab
# Purpose:
#   Clean the 6 selected cBioPortal files before SQL loading.
#   This version matches the FINAL normalized ERD:
#
#   PATIENT
#   PATIENT_DEMOGRAPHIC
#   PATIENT_CLINICAL
#   PATIENT_SURVIVAL
#   PATIENT_SMOKING_HISTORY
#   CANCER_TYPE
#   SAMPLE
#   SAMPLE_STAGE
#   SAMPLE_METRIC
#   GENE
#   GENOMIC_VARIANT
#   VARIANT_ANNOTATION
#   SAMPLE_MUTATION
#   COPY_NUMBER_ALTERATION
#   MRNA_EXPRESSION
#   PROTEIN_EXPRESSION
#
#   This does NOT create SQL AUTO_INCREMENT IDs.
#   SQL will later create numeric primary keys.
# ============================================================

import os
import re
import zipfile
import hashlib
from pathlib import Path

import pandas as pd
import numpy as np

from google.colab import drive
from google.colab import files


# ============================================================
# 1. MOUNT GOOGLE DRIVE
# ============================================================

drive.mount("/content/drive")


# ============================================================
# 2. CONFIGURATION
# ============================================================

FOLDER_NAME = "luad_tcga_pub"

OUTPUT_DIR = Path("/content/luad_cleaned_outputs")
ZIP_PATH = Path("/content/luad_cleaned_staging_files.zip")

OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

FILES_REQUIRED = {
    "clinical_patient": "data_clinical_patient.txt",
    "clinical_sample": "data_clinical_sample.txt",
    "mutations": "data_mutations.txt",
    "cna": "data_cna.txt",
    "mrna": "data_mrna_seq_v2_rsem.txt",
    "rppa": "data_rppa.txt"
}

MISSING_VALUES = [
    "NA", "N/A", "NaN", "nan", "NULL", "null",
    "[Not Available]", "Not Available", "Unknown",
    "Not Reported", "Not Applicable", "", " "
]


# ============================================================
# 3. FIND DATA FOLDER
# ============================================================

def find_data_folder(folder_name):
    possible_paths = [
        Path(f"/content/drive/MyDrive/{folder_name}"),
        Path(f"/content/drive/My Drive/{folder_name}"),
        Path(f"/content/drive/MyDrive/Colab Notebooks/{folder_name}"),
        Path(f"/content/drive/My Drive/Colab Notebooks/{folder_name}")
    ]

    for path in possible_paths:
        if path.exists():
            return path

    print("Searching Google Drive for folder...")

    for root, dirs, filenames in os.walk("/content/drive"):
        if Path(root).name == folder_name:
            return Path(root)

    raise FileNotFoundError(
        f"Could not find folder named '{folder_name}'. "
        f"Please check the folder name in Google Drive."
    )


DATA_DIR = find_data_folder(FOLDER_NAME)
print(f"Using data folder: {DATA_DIR}")


# ============================================================
# 4. HELPER FUNCTIONS
# ============================================================

def clean_column_name(col):
    col = str(col).strip()
    col = col.replace(" ", "_")
    col = col.replace("-", "_")
    col = col.replace("/", "_")
    col = re.sub(r"[^A-Za-z0-9_]", "", col)
    return col.upper()


def make_unique_columns(columns):
    seen = {}
    new_cols = []

    for col in columns:
        base = clean_column_name(col)

        if base not in seen:
            seen[base] = 1
            new_cols.append(base)
        else:
            seen[base] += 1
            new_cols.append(f"{base}_{seen[base]}")

    return new_cols


def read_cbioportal_file(path):
    path = Path(path)

    if not path.exists():
        raise FileNotFoundError(f"Missing file: {path}")

    df = pd.read_csv(
        path,
        sep="\t",
        comment="#",
        dtype=str,
        low_memory=False
    )

    df.columns = make_unique_columns(df.columns)
    df = df.replace(MISSING_VALUES, np.nan)

    return df


def find_column(df, candidates):
    cols = list(df.columns)

    for candidate in candidates:
        candidate_clean = clean_column_name(candidate)

        if candidate_clean in cols:
            return candidate_clean

        for col in cols:
            if col == candidate_clean or col.startswith(candidate_clean + "_"):
                return col

    return None


def get_series(df, col):
    if col is None or col not in df.columns:
        return pd.Series([np.nan] * len(df))

    value = df[col]

    if isinstance(value, pd.DataFrame):
        return value.iloc[:, 0]

    return value


def safe_get(df, candidates):
    col = find_column(df, candidates)
    return get_series(df, col)


def standardize_sample_barcode(value):
    if pd.isna(value):
        return np.nan

    value = str(value).strip()
    value = value.replace("_", "-")
    return value


def derive_patient_barcode_from_sample(sample_barcode):
    if pd.isna(sample_barcode):
        return np.nan

    sample_barcode = str(sample_barcode).strip().replace("_", "-")

    if sample_barcode.startswith("TCGA") and len(sample_barcode) >= 12:
        return sample_barcode[:12]

    return sample_barcode


def standardize_gene_symbol(value):
    if pd.isna(value):
        return np.nan

    value = str(value).strip()

    if value == "":
        return np.nan

    if "|" in value:
        value = value.split("|")[0]

    return value.upper()


def parse_rppa_gene(value):
    if pd.isna(value):
        return np.nan

    value = str(value).strip()

    if "|" in value:
        return value.split("|")[0].strip().upper()

    return value.strip().upper()


def parse_rppa_antibody(value):
    if pd.isna(value):
        return np.nan

    value = str(value).strip()

    if "|" in value:
        return value.split("|", 1)[1].strip()

    return value


def to_numeric_clean(series):
    return pd.to_numeric(series, errors="coerce")


def save_csv(df, filename):
    path = OUTPUT_DIR / filename
    df.to_csv(path, index=False)
    print(f"Saved {filename}: {len(df):,} rows")
    return path


def identify_matrix_gene_column(df):
    gene_col = find_column(df, [
        "HUGO_SYMBOL",
        "GENE",
        "GENE_SYMBOL",
        "HUGO_GENE_SYMBOL"
    ])

    if gene_col:
        return gene_col

    return df.columns[0]


def identify_matrix_annotation_columns(df):
    annotation_candidates = [
        "HUGO_SYMBOL",
        "GENE",
        "GENE_SYMBOL",
        "HUGO_GENE_SYMBOL",
        "ENTREZ_GENE_ID",
        "GENE_ID",
        "CYTOBAND",
        "DESCRIPTION",
        "ANTIBODY_REF",
        "PROTEIN_NAME",
        "RPPA_ID",
        "COMPOSITE_ELEMENT_REF",
        "ENTITY_STABLE_ID",
        "REFSEQ_PROTEIN_ID"
    ]

    annotation_cols = []

    for candidate in annotation_candidates:
        col = find_column(df, [candidate])
        if col and col not in annotation_cols:
            annotation_cols.append(col)

    if len(annotation_cols) == 0:
        annotation_cols.append(df.columns[0])

    return annotation_cols


def get_matrix_sample_columns(df):
    annotation_cols = identify_matrix_annotation_columns(df)
    return [c for c in df.columns if c not in annotation_cols]


def make_variant_hash_from_values(
    chromosome,
    start_position,
    end_position,
    reference_allele,
    tumor_seq_allele1,
    tumor_seq_allele2
):
    raw = "|".join([
        "" if pd.isna(chromosome) else str(chromosome),
        "" if pd.isna(start_position) else str(start_position),
        "" if pd.isna(end_position) else str(end_position),
        "" if pd.isna(reference_allele) else str(reference_allele),
        "" if pd.isna(tumor_seq_allele1) else str(tumor_seq_allele1),
        "" if pd.isna(tumor_seq_allele2) else str(tumor_seq_allele2)
    ])

    return hashlib.sha256(raw.encode("utf-8")).hexdigest()


def make_variant_hash(row):
    return make_variant_hash_from_values(
        row.get("CHROMOSOME"),
        row.get("START_POSITION"),
        row.get("END_POSITION"),
        row.get("REFERENCE_ALLELE"),
        row.get("TUMOR_SEQ_ALLELE1"),
        row.get("TUMOR_SEQ_ALLELE2")
    )


def clean_output_folder():
    for file in OUTPUT_DIR.glob("*"):
        file.unlink()


clean_output_folder()


# ============================================================
# 5. LOAD RAW FILES
# ============================================================

print("\nChecking required files...")

for label, filename in FILES_REQUIRED.items():
    path = DATA_DIR / filename
    if not path.exists():
        raise FileNotFoundError(f"Missing required file: {path}")

print("All required files found.")

print("\nReading raw files...")

clinical_patient = read_cbioportal_file(DATA_DIR / FILES_REQUIRED["clinical_patient"])
clinical_sample = read_cbioportal_file(DATA_DIR / FILES_REQUIRED["clinical_sample"])
mutations = read_cbioportal_file(DATA_DIR / FILES_REQUIRED["mutations"])
cna = read_cbioportal_file(DATA_DIR / FILES_REQUIRED["cna"])
mrna = read_cbioportal_file(DATA_DIR / FILES_REQUIRED["mrna"])
rppa = read_cbioportal_file(DATA_DIR / FILES_REQUIRED["rppa"])

print("Raw files loaded.")


# ============================================================
# 6. CLEAN CLINICAL PATIENT FILE
# ============================================================

patient_col = find_column(clinical_patient, ["PATIENT_ID", "PATIENT_BARCODE", "CASE_ID"])

if patient_col is None:
    raise ValueError("Could not find patient identifier column in clinical patient file.")

clinical_patient_clean = pd.DataFrame()

clinical_patient_clean["PATIENT_BARCODE"] = (
    get_series(clinical_patient, patient_col)
    .astype(str)
    .str.strip()
)

clinical_patient_clean["SEX"] = safe_get(clinical_patient, ["SEX", "GENDER"])
clinical_patient_clean["AGE"] = to_numeric_clean(safe_get(clinical_patient, ["AGE", "AGE_AT_DIAGNOSIS"]))

clinical_patient_clean["HISTOLOGICAL_SUBTYPE"] = safe_get(clinical_patient, [
    "HISTOLOGICAL_SUBTYPE",
    "CANCER_TYPE_DETAILED",
    "SUBTYPE"
])

clinical_patient_clean["PRETREATMENT_HISTORY"] = safe_get(clinical_patient, [
    "PRETREATMENT_HISTORY"
])

clinical_patient_clean["PRIMARY_TUMOR_PATHOLOGIC_SPREAD"] = safe_get(clinical_patient, [
    "PRIMARY_TUMOR_PATHOLOGIC_SPREAD",
    "PRIMARY_TUMOR_SPREAD"
])

clinical_patient_clean["PRIOR_DIAGNOSIS"] = safe_get(clinical_patient, [
    "PRIOR_DIAGNOSIS"
])

clinical_patient_clean["RESIDUAL_TUMOR"] = safe_get(clinical_patient, [
    "RESIDUAL_TUMOR"
])

clinical_patient_clean["TOBACCO_SMOKING_HISTORY_INDICATOR"] = safe_get(clinical_patient, [
    "TOBACCO_SMOKING_HISTORY_INDICATOR",
    "TOBACCO_SMOKING_HISTORY",
    "SMOKING_HISTORY",
    "CIGARETTE_SMOKING_HISTORY"
])

clinical_patient_clean["OS_STATUS"] = safe_get(clinical_patient, [
    "OS_STATUS",
    "OVERALL_SURVIVAL_STATUS"
])

clinical_patient_clean["OS_MONTHS"] = to_numeric_clean(safe_get(clinical_patient, [
    "OS_MONTHS",
    "OVERALL_SURVIVAL_MONTHS"
]))

clinical_patient_clean = clinical_patient_clean.replace(MISSING_VALUES, np.nan)
clinical_patient_clean = clinical_patient_clean.dropna(subset=["PATIENT_BARCODE"])
clinical_patient_clean = clinical_patient_clean.drop_duplicates(subset=["PATIENT_BARCODE"])

save_csv(clinical_patient_clean, "clinical_patient_clean.csv")


# ============================================================
# 7. CLEAN CLINICAL SAMPLE FILE
# ============================================================

sample_col = find_column(clinical_sample, ["SAMPLE_ID", "SAMPLE_BARCODE", "TUMOR_SAMPLE_BARCODE"])
sample_patient_col = find_column(clinical_sample, ["PATIENT_ID", "PATIENT_BARCODE", "CASE_ID"])

if sample_col is None:
    raise ValueError("Could not find sample identifier column in clinical sample file.")

clinical_sample_clean = pd.DataFrame()

clinical_sample_clean["SAMPLE_BARCODE"] = (
    get_series(clinical_sample, sample_col)
    .apply(standardize_sample_barcode)
)

if sample_patient_col:
    clinical_sample_clean["PATIENT_BARCODE"] = (
        get_series(clinical_sample, sample_patient_col)
        .astype(str)
        .str.strip()
    )
else:
    clinical_sample_clean["PATIENT_BARCODE"] = clinical_sample_clean["SAMPLE_BARCODE"].apply(
        derive_patient_barcode_from_sample
    )

clinical_sample_clean["CANCER_TYPE"] = safe_get(clinical_sample, ["CANCER_TYPE"])
clinical_sample_clean["CANCER_TYPE_DETAILED"] = safe_get(clinical_sample, ["CANCER_TYPE_DETAILED"])
clinical_sample_clean["ONCOTREE_CODE"] = safe_get(clinical_sample, ["ONCOTREE_CODE"])
clinical_sample_clean["SAMPLE_TYPE"] = safe_get(clinical_sample, ["SAMPLE_TYPE"])
clinical_sample_clean["SOMATIC_STATUS"] = safe_get(clinical_sample, ["SOMATIC_STATUS"])

clinical_sample_clean["TUMOR_STAGE_2009"] = safe_get(clinical_sample, [
    "TUMOR_STAGE_2009",
    "AJCC_PATHOLOGIC_TUMOR_STAGE",
    "PATHOLOGIC_STAGE"
])

clinical_sample_clean["DISTANT_METASTASIS_PATHOLOGIC_SPREAD"] = safe_get(clinical_sample, [
    "DISTANT_METASTASIS_PATHOLOGIC_SPREAD",
    "DISTANT_METASTASIS_SPREAD",
    "AJCC_METASTASIS_PATHOLOGIC_PM"
])

clinical_sample_clean["TMB_NONSYNONYMOUS"] = to_numeric_clean(safe_get(clinical_sample, [
    "TMB_NONSYNONYMOUS",
    "TMB",
    "TUMOR_MUTATION_BURDEN"
]))

clinical_sample_clean = clinical_sample_clean.replace(MISSING_VALUES, np.nan)
clinical_sample_clean = clinical_sample_clean.dropna(subset=["SAMPLE_BARCODE", "PATIENT_BARCODE"])
clinical_sample_clean = clinical_sample_clean.drop_duplicates(subset=["SAMPLE_BARCODE"])

save_csv(clinical_sample_clean, "clinical_sample_clean.csv")


# ============================================================
# 8. CREATE CANCER TYPE REFERENCE SOURCE FILE
# ============================================================

cancer_type_ref_source = (
    clinical_sample_clean[
        ["CANCER_TYPE", "CANCER_TYPE_DETAILED", "ONCOTREE_CODE"]
    ]
    .drop_duplicates()
    .reset_index(drop=True)
)

save_csv(cancer_type_ref_source, "cancer_type_ref_source.csv")


# ============================================================
# 9. CLEAN MUTATION FILE FOR FINAL NORMALIZED ERD
# ============================================================

mutation_col_map = {
    "HUGO_SYMBOL": ["HUGO_SYMBOL", "GENE", "GENE_SYMBOL"],
    "ENTREZ_GENE_ID": ["ENTREZ_GENE_ID", "ENTREZ_GENEID", "GENE_ID"],
    "CHROMOSOME": ["CHROMOSOME", "CHROM"],
    "START_POSITION": ["START_POSITION", "START"],
    "END_POSITION": ["END_POSITION", "END"],
    "CONSEQUENCE": ["CONSEQUENCE"],
    "VARIANT_CLASSIFICATION": ["VARIANT_CLASSIFICATION"],
    "VARIANT_TYPE": ["VARIANT_TYPE"],
    "REFERENCE_ALLELE": ["REFERENCE_ALLELE", "REF"],
    "TUMOR_SEQ_ALLELE1": ["TUMOR_SEQ_ALLELE1"],
    "TUMOR_SEQ_ALLELE2": ["TUMOR_SEQ_ALLELE2", "ALT", "TUMOR_ALLELE"],
    "TUMOR_SAMPLE_BARCODE": ["TUMOR_SAMPLE_BARCODE", "SAMPLE_ID", "SAMPLE_BARCODE"],
    "T_REF_COUNT": ["T_REF_COUNT", "TUMOR_REF_COUNT"],
    "T_ALT_COUNT": ["T_ALT_COUNT", "TUMOR_ALT_COUNT"],
    "HGVSC": ["HGVSC"],
    "HGVSP": ["HGVSP"],
    "HGVSP_SHORT": ["HGVSP_SHORT"],
    "TRANSCRIPT_ID": ["TRANSCRIPT_ID"],
    "PROTEIN_POSITION": ["PROTEIN_POSITION"],
    "CODONS": ["CODONS"],
    "HOTSPOT": ["HOTSPOT"],
    "IMPACT": ["IMPACT"]
}

mutation_clean = pd.DataFrame()

for output_col, candidates in mutation_col_map.items():
    mutation_clean[output_col] = safe_get(mutations, candidates)

mutation_clean["HUGO_SYMBOL"] = mutation_clean["HUGO_SYMBOL"].apply(standardize_gene_symbol)
mutation_clean["TUMOR_SAMPLE_BARCODE"] = mutation_clean["TUMOR_SAMPLE_BARCODE"].apply(standardize_sample_barcode)

mutation_clean["ENTREZ_GENE_ID"] = to_numeric_clean(mutation_clean["ENTREZ_GENE_ID"]).astype("Int64")
mutation_clean["START_POSITION"] = to_numeric_clean(mutation_clean["START_POSITION"]).astype("Int64")
mutation_clean["END_POSITION"] = to_numeric_clean(mutation_clean["END_POSITION"]).astype("Int64")
mutation_clean["T_REF_COUNT"] = to_numeric_clean(mutation_clean["T_REF_COUNT"]).astype("Int64")
mutation_clean["T_ALT_COUNT"] = to_numeric_clean(mutation_clean["T_ALT_COUNT"]).astype("Int64")

mutation_clean = mutation_clean.replace(MISSING_VALUES, np.nan)

mutation_required_cols = [
    "HUGO_SYMBOL",
    "CHROMOSOME",
    "START_POSITION",
    "END_POSITION",
    "TUMOR_SAMPLE_BARCODE"
]

mutation_clean = mutation_clean.dropna(subset=mutation_required_cols)

# Final ERD variant key: raw variant facts only.
variant_key_cols = [
    "CHROMOSOME",
    "START_POSITION",
    "END_POSITION",
    "REFERENCE_ALLELE",
    "TUMOR_SEQ_ALLELE1",
    "TUMOR_SEQ_ALLELE2"
]

# Add VARIANT_HASH for easier SQL loading into GENOMIC_VARIANT.
mutation_clean["VARIANT_HASH"] = mutation_clean.apply(make_variant_hash, axis=1)

annotation_cols = [
    "HUGO_SYMBOL",
    "ENTREZ_GENE_ID",
    "VARIANT_CLASSIFICATION",
    "VARIANT_TYPE",
    "CONSEQUENCE",
    "IMPACT",
    "HGVSC",
    "HGVSP",
    "HGVSP_SHORT",
    "TRANSCRIPT_ID",
    "PROTEIN_POSITION",
    "CODONS",
    "HOTSPOT"
]

# Full cleaned mutation audit file.
mutation_clean_full_source = mutation_clean.copy()

# GENOMIC_VARIANT staging source.
# One row per raw genomic variant.
genomic_variant_source = (
    mutation_clean[
        variant_key_cols + ["VARIANT_HASH"]
    ]
    .drop_duplicates(subset=["VARIANT_HASH"])
    .reset_index(drop=True)
)

# VARIANT_ANNOTATION staging source.
# Annotation belongs to variant + gene/transcript/effect.
variant_annotation_source = (
    mutation_clean[
        ["VARIANT_HASH"] + annotation_cols
    ]
    .drop_duplicates()
    .reset_index(drop=True)
)

# SAMPLE_MUTATION staging source.
# Sample-specific observation of a variant.
sample_mutation_source = (
    mutation_clean[
        ["TUMOR_SAMPLE_BARCODE", "VARIANT_HASH", "T_REF_COUNT", "T_ALT_COUNT"]
    ]
    .rename(columns={"TUMOR_SAMPLE_BARCODE": "SAMPLE_BARCODE"})
    .drop_duplicates()
    .reset_index(drop=True)
)

save_csv(mutation_clean_full_source, "mutation_clean_full_source.csv")
save_csv(genomic_variant_source, "genomic_variant_source.csv")
save_csv(variant_annotation_source, "variant_annotation_source.csv")
save_csv(sample_mutation_source, "sample_mutation_source.csv")


# ============================================================
# 10. CREATE INITIAL GENE SOURCE FROM MUTATION DATA
# ============================================================

gene_frames = []

genes_from_mutations = (
    mutation_clean[["HUGO_SYMBOL", "ENTREZ_GENE_ID"]]
    .dropna(subset=["HUGO_SYMBOL"])
    .drop_duplicates()
)

gene_frames.append(genes_from_mutations)


# ============================================================
# 11. CLEAN CNA / MRNA / RPPA MATRIX FILES INTO LONG FORMAT
# ============================================================

def clean_matrix_to_long(
    df,
    output_filename,
    value_column_name,
    gene_source_name,
    is_rppa=False,
    chunk_size=1000
):
    """
    Converts wide matrix file into long format without creating SQL IDs.

    Output format for CNA and mRNA:
    - SAMPLE_BARCODE
    - HUGO_SYMBOL
    - VALUE_COLUMN

    Output format for RPPA:
    - SAMPLE_BARCODE
    - HUGO_SYMBOL
    - ANTIBODY_REF
    - EXPRESSION_VALUE
    """

    gene_col = identify_matrix_gene_column(df)
    annotation_cols = identify_matrix_annotation_columns(df)
    sample_cols = [c for c in df.columns if c not in annotation_cols]

    output_path = OUTPUT_DIR / output_filename

    if output_path.exists():
        output_path.unlink()

    first_write = True
    total_rows = 0
    gene_rows = []

    for start in range(0, len(df), chunk_size):
        chunk = df.iloc[start:start + chunk_size].copy()

        if is_rppa:
            feature_series = get_series(chunk, gene_col)
            chunk["HUGO_SYMBOL_CLEAN"] = feature_series.apply(parse_rppa_gene)
            chunk["ANTIBODY_REF_CLEAN"] = feature_series.apply(parse_rppa_antibody)

            id_vars = ["HUGO_SYMBOL_CLEAN", "ANTIBODY_REF_CLEAN"]

            long_df = chunk[id_vars + sample_cols].melt(
                id_vars=id_vars,
                value_vars=sample_cols,
                var_name="SAMPLE_BARCODE",
                value_name=value_column_name
            )

            long_df["SAMPLE_BARCODE"] = long_df["SAMPLE_BARCODE"].apply(standardize_sample_barcode)
            long_df["HUGO_SYMBOL"] = long_df["HUGO_SYMBOL_CLEAN"].apply(standardize_gene_symbol)
            long_df["ANTIBODY_REF"] = long_df["ANTIBODY_REF_CLEAN"]
            long_df[value_column_name] = to_numeric_clean(long_df[value_column_name])

            long_df = long_df.dropna(subset=["SAMPLE_BARCODE", "HUGO_SYMBOL", value_column_name])

            long_df = long_df[
                ["SAMPLE_BARCODE", "HUGO_SYMBOL", "ANTIBODY_REF", value_column_name]
            ]

            gene_rows.append(
                long_df[["HUGO_SYMBOL"]].drop_duplicates()
            )

        else:
            chunk["HUGO_SYMBOL_CLEAN"] = get_series(chunk, gene_col).apply(standardize_gene_symbol)

            long_df = chunk[["HUGO_SYMBOL_CLEAN"] + sample_cols].melt(
                id_vars=["HUGO_SYMBOL_CLEAN"],
                value_vars=sample_cols,
                var_name="SAMPLE_BARCODE",
                value_name=value_column_name
            )

            long_df["SAMPLE_BARCODE"] = long_df["SAMPLE_BARCODE"].apply(standardize_sample_barcode)
            long_df["HUGO_SYMBOL"] = long_df["HUGO_SYMBOL_CLEAN"].apply(standardize_gene_symbol)
            long_df[value_column_name] = to_numeric_clean(long_df[value_column_name])

            long_df = long_df.dropna(subset=["SAMPLE_BARCODE", "HUGO_SYMBOL", value_column_name])

            long_df = long_df[
                ["SAMPLE_BARCODE", "HUGO_SYMBOL", value_column_name]
            ]

            gene_rows.append(
                long_df[["HUGO_SYMBOL"]].drop_duplicates()
            )

        long_df.to_csv(
            output_path,
            mode="w" if first_write else "a",
            index=False,
            header=first_write
        )

        total_rows += len(long_df)
        first_write = False

        print(f"{output_filename}: processed rows {start:,} to {min(start + chunk_size, len(df)):,}")

    if len(gene_rows) > 0:
        gene_source = pd.concat(gene_rows, ignore_index=True).drop_duplicates()
        gene_source["ENTREZ_GENE_ID"] = pd.NA
        gene_source = gene_source[["HUGO_SYMBOL", "ENTREZ_GENE_ID"]]
    else:
        gene_source = pd.DataFrame(columns=["HUGO_SYMBOL", "ENTREZ_GENE_ID"])

    gene_source_file = OUTPUT_DIR / gene_source_name
    gene_source.to_csv(gene_source_file, index=False)

    print(f"Saved {output_filename}: {total_rows:,} rows")
    print(f"Saved {gene_source_name}: {len(gene_source):,} genes")

    return gene_source


print("\nCleaning CNA matrix...")

cna_gene_source = clean_matrix_to_long(
    cna,
    "cna_long_clean.csv",
    "CNA_VALUE",
    "gene_source_cna.csv",
    is_rppa=False,
    chunk_size=1000
)

gene_frames.append(cna_gene_source)


print("\nCleaning mRNA matrix...")

mrna_gene_source = clean_matrix_to_long(
    mrna,
    "mrna_long_clean.csv",
    "RSEM_VALUE",
    "gene_source_mrna.csv",
    is_rppa=False,
    chunk_size=1000
)

gene_frames.append(mrna_gene_source)


print("\nCleaning RPPA matrix...")

rppa_gene_source = clean_matrix_to_long(
    rppa,
    "rppa_long_clean.csv",
    "EXPRESSION_VALUE",
    "gene_source_rppa.csv",
    is_rppa=True,
    chunk_size=1000
)

gene_frames.append(rppa_gene_source)


# ============================================================
# 12. CREATE FINAL GENE SOURCE FILE
# ============================================================

gene_source_all = pd.concat(gene_frames, ignore_index=True)

gene_source_all["HUGO_SYMBOL"] = gene_source_all["HUGO_SYMBOL"].apply(standardize_gene_symbol)
gene_source_all["ENTREZ_GENE_ID"] = to_numeric_clean(gene_source_all["ENTREZ_GENE_ID"]).astype("Int64")

gene_source_all = gene_source_all.dropna(subset=["HUGO_SYMBOL"])

# Prefer rows where ENTREZ_GENE_ID exists.
gene_source_all["HAS_ENTREZ"] = gene_source_all["ENTREZ_GENE_ID"].notna().astype(int)

gene_source_all = (
    gene_source_all
    .sort_values(["HUGO_SYMBOL", "HAS_ENTREZ"], ascending=[True, False])
    .drop_duplicates(subset=["HUGO_SYMBOL"], keep="first")
    .drop(columns=["HAS_ENTREZ"])
    .reset_index(drop=True)
)

save_csv(gene_source_all, "gene_source_all.csv")


# ============================================================
# 13. VALIDATION REPORT
# ============================================================

validation_rows = []

def add_validation(name, value):
    validation_rows.append({
        "CHECK_NAME": name,
        "VALUE": value
    })


add_validation("clinical_patient_clean_rows", len(clinical_patient_clean))
add_validation("clinical_sample_clean_rows", len(clinical_sample_clean))
add_validation("cancer_type_ref_source_rows", len(cancer_type_ref_source))
add_validation("mutation_clean_full_source_rows", len(mutation_clean_full_source))
add_validation("genomic_variant_source_unique_variants", len(genomic_variant_source))
add_validation("variant_annotation_source_rows", len(variant_annotation_source))
add_validation("sample_mutation_source_rows", len(sample_mutation_source))
add_validation("gene_source_all_rows", len(gene_source_all))

# Compare sample overlap after standardization.
clinical_samples = set(clinical_sample_clean["SAMPLE_BARCODE"].dropna())
mutation_samples = set(sample_mutation_source["SAMPLE_BARCODE"].dropna())

add_validation("mutation_samples_found_in_clinical_sample", len(mutation_samples & clinical_samples))
add_validation("mutation_samples_not_found_in_clinical_sample", len(mutation_samples - clinical_samples))

# Compare patient overlap.
clinical_patients = set(clinical_patient_clean["PATIENT_BARCODE"].dropna())
sample_patients = set(clinical_sample_clean["PATIENT_BARCODE"].dropna())

add_validation("sample_patients_found_in_clinical_patient", len(sample_patients & clinical_patients))
add_validation("sample_patients_not_found_in_clinical_patient", len(sample_patients - clinical_patients))

# Count long files by reading only line counts.
def count_csv_data_rows(path):
    path = Path(path)
    if not path.exists():
        return 0

    with open(path, "r") as f:
        return max(sum(1 for _ in f) - 1, 0)


add_validation("cna_long_clean_rows", count_csv_data_rows(OUTPUT_DIR / "cna_long_clean.csv"))
add_validation("mrna_long_clean_rows", count_csv_data_rows(OUTPUT_DIR / "mrna_long_clean.csv"))
add_validation("rppa_long_clean_rows", count_csv_data_rows(OUTPUT_DIR / "rppa_long_clean.csv"))

# Duplicate checks.
add_validation(
    "duplicate_patient_barcodes",
    clinical_patient_clean["PATIENT_BARCODE"].duplicated().sum()
)

add_validation(
    "duplicate_sample_barcodes",
    clinical_sample_clean["SAMPLE_BARCODE"].duplicated().sum()
)

add_validation(
    "duplicate_variant_hashes_in_genomic_variant_source",
    genomic_variant_source["VARIANT_HASH"].duplicated().sum()
)

validation_report = pd.DataFrame(validation_rows)
save_csv(validation_report, "validation_report.csv")

print("\nValidation Report:")
display(validation_report)


# ============================================================
# 14. CREATE README FILE
# ============================================================

readme_text = """
LUAD Cleaned Staging Files
==========================

These files are cleaned staging files only.
They do NOT contain SQL AUTO_INCREMENT IDs.
The SQL database will generate numeric IDs during loading.

Files created:

1. clinical_patient_clean.csv
   Clean patient-level fields:
   PATIENT_BARCODE, SEX, AGE, clinical fields, smoking history, OS_STATUS, OS_MONTHS.

   Supports:
   - PATIENT
   - PATIENT_DEMOGRAPHIC
   - PATIENT_CLINICAL
   - PATIENT_SURVIVAL
   - PATIENT_SMOKING_HISTORY

2. clinical_sample_clean.csv
   Clean sample-level fields:
   SAMPLE_BARCODE, PATIENT_BARCODE, cancer type fields, sample type, somatic status,
   tumor stage, metastasis, and TMB.

   Supports:
   - SAMPLE
   - SAMPLE_STAGE
   - SAMPLE_METRIC

   Note:
   SAMPLE_TYPE is retained for audit/usefulness, but load it only if your final SQL schema
   includes SAMPLE_TYPE.

3. cancer_type_ref_source.csv
   Distinct cancer type combinations:
   CANCER_TYPE, CANCER_TYPE_DETAILED, ONCOTREE_CODE.

   Supports:
   - CANCER_TYPE

4. mutation_clean_full_source.csv
   Full cleaned mutation staging file with selected biologically useful columns.
   This file is useful for audit/debugging.

5. genomic_variant_source.csv
   Unique raw genomic variants based on:
   CHROMOSOME, START_POSITION, END_POSITION, REFERENCE_ALLELE,
   TUMOR_SEQ_ALLELE1, TUMOR_SEQ_ALLELE2, VARIANT_HASH.

   Supports:
   - GENOMIC_VARIANT

6. variant_annotation_source.csv
   Variant annotation records including:
   VARIANT_HASH, HUGO_SYMBOL, ENTREZ_GENE_ID, VARIANT_CLASSIFICATION,
   VARIANT_TYPE, CONSEQUENCE, IMPACT, HGVSC, HGVSP, HGVSP_SHORT,
   TRANSCRIPT_ID, PROTEIN_POSITION, CODONS, HOTSPOT.

   Supports:
   - VARIANT_ANNOTATION

7. sample_mutation_source.csv
   Sample-specific mutation observations:
   SAMPLE_BARCODE, VARIANT_HASH, T_REF_COUNT, T_ALT_COUNT.

   Supports:
   - SAMPLE_MUTATION

8. cna_long_clean.csv
   Long-format CNA records:
   SAMPLE_BARCODE, HUGO_SYMBOL, CNA_VALUE.

   Supports:
   - COPY_NUMBER_ALTERATION

9. mrna_long_clean.csv
   Long-format mRNA records:
   SAMPLE_BARCODE, HUGO_SYMBOL, RSEM_VALUE.

   Supports:
   - MRNA_EXPRESSION

10. rppa_long_clean.csv
    Long-format RPPA records:
    SAMPLE_BARCODE, HUGO_SYMBOL, ANTIBODY_REF, EXPRESSION_VALUE.

    Supports:
    - PROTEIN_EXPRESSION

11. gene_source_all.csv
    Combined clean gene list from mutation, CNA, mRNA, and RPPA files.

    Supports:
    - GENE

12. validation_report.csv
    Basic row counts, duplicate checks, and overlap checks.

Important cleaning rules applied:
- Missing values converted to blank/NULL-ready values.
- Sample IDs standardized by replacing underscores with hyphens.
- TCGA patient barcodes derived from sample barcodes when needed.
- Gene symbols standardized to uppercase.
- RPPA identifiers parsed into HUGO_SYMBOL and ANTIBODY_REF.
- CNA, mRNA, and RPPA matrices converted from wide format to long format.
- Mutation data split according to final ERD:
  raw variant facts -> GENOMIC_VARIANT,
  biological annotation -> VARIANT_ANNOTATION,
  sample-specific read counts -> SAMPLE_MUTATION.
- VARIANT_HASH generated for stable loading into GENOMIC_VARIANT.
- No SQL primary keys were manually generated.
"""

with open(OUTPUT_DIR / "README_cleaning_pipeline.txt", "w") as f:
    f.write(readme_text)


# ============================================================
# 15. ZIP AND DOWNLOAD OUTPUTS
# ============================================================

if ZIP_PATH.exists():
    ZIP_PATH.unlink()

with zipfile.ZipFile(ZIP_PATH, "w", zipfile.ZIP_DEFLATED) as zipf:
    for file_path in OUTPUT_DIR.glob("*"):
        zipf.write(file_path, arcname=file_path.name)

print("\n============================================================")
print("CLEANING COMPLETE")
print("============================================================")
print(f"Cleaned files saved to: {OUTPUT_DIR}")
print(f"ZIP file created at: {ZIP_PATH}")
print("Downloading ZIP to your laptop...")
print("============================================================")

files.download(str(ZIP_PATH))

